# Generated by Django 5.1.6 on 2026-07-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'alerta de inventario',
                'verbose_name_plural': 'alertas de inventario',
                'db_table': 'alertas_inventario',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20)),
                ('motivo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('ajuste_manual', 'Ajuste manual'), ('merma', 'Merma')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
