# Generated by Django 5.1.6 on 2026-07-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=60)),
                ('entidad', models.CharField(max_length=60)),
                ('entidad_id', models.CharField(max_length=60)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'db_table': 'logs_auditoria',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
